Description: >
  JPSalado / Project2: Udagram / BastionHost


Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String


Resources:
# Bastion Host
  BastionHost:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0d6621c01e8c2de2c
      KeyName: BastionHost
      InstanceType: t2.micro
      NetworkInterfaces: 
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        GroupSet:
          - !Ref BastionHostSecGroup
        SubnetId:
          Fn::ImportValue: !Sub ${EnvironmentName}-PUB1-SN

  BastionHostSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Restrict inbound internet traffic to my IP and restrict all outbound internet traffic
      VpcId:
        Fn::ImportValue: !Sub ${EnvironmentName}-VPCID
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 46.6.1.101/32